module Stateful
  CURRENT_STATE = 'CURRENT'
  UPDATED_STATE = 'UPDATED'
  DELETED_STATE = 'DELETED'
  CANCEL_STATE = 'CANCEL'

  STATES = [CURRENT_STATE, CANCEL_STATE, DELETED_STATE, UPDATED_STATE]
end